### PR TITLE
6 fix jwt authentication

### LINKED ISSUE #6: fix jwt authentication

### PR DESCRIPTION
**Pull request by Xemii16**
Added support for JWT tokens. Entry is made only through mail. Closes #6

### CODE REVIEW

File: src/main/java/com/balamut/yejournal/ApplicationConfiguration.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+@Configuration
+@RequiredArgsConstructor
+public class ApplicationConfiguration {
+
+    private final UserRepository repository;
+    private final UserDetailsService userDetailsService;
+
+    @Bean
+    public AuthenticationProvider authenticationProvider(){
```
Comment (Xemii16) [inline src/main/java/com/balamut/yejournal/ApplicationConfiguration.java:23]: Authentication provider

File: src/main/java/com/balamut/yejournal/ApplicationConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+        DaoAuthenticationProvider authenticationProvider = new DaoAuthenticationProvider();
+        authenticationProvider.setUserDetailsService(userDetailsService);
+        authenticationProvider.setPasswordEncoder(passwordEncoder());
+        return authenticationProvider;
+    }
+
+    @Bean
+    public AuthenticationManager authenticationManager(AuthenticationConfiguration configuration) throws Exception {
```
Comment (Xemii16) [inline src/main/java/com/balamut/yejournal/ApplicationConfiguration.java:31]: AuthenticationManager

File: src/main/java/com/balamut/yejournal/entity/User.java [hunk 3]
```diff
@@ -28,4 +33,37 @@ public class User {
             inverseJoinColumns = @JoinColumn(name = "role_id")
     )
     private List<Role> roles;
```
Comment (Xemii16) [inline src/main/java/com/balamut/yejournal/entity/User.java:35]: Maybe will be fixed
